// Spelling Bee word bank.
// Each word: w = word, s = example sentence, d = simple kid-friendly definition.
// Levels grow harder. Great for ages 6-8 (Scripps-style early grade bee).

const WORD_LEVELS = {
  "Level 1 — Starter (3-4 letters)": [
    { w: "cat", s: "The cat sat on the mat.", d: "A small furry pet that says meow." },
    { w: "dog", s: "My dog likes to run.", d: "A friendly pet that barks." },
    { w: "sun", s: "The sun is bright today.", d: "The big star that gives us light and warmth." },
    { w: "hat", s: "Put on your hat before you go out.", d: "Something you wear on your head." },
    { w: "red", s: "The apple is red.", d: "The color of a strawberry or fire truck." },
    { w: "run", s: "I can run very fast.", d: "To move quickly on your feet." },
    { w: "big", s: "The elephant is big.", d: "Large in size." },
    { w: "cup", s: "She drank milk from the cup.", d: "A small container you drink from." },
    { w: "bed", s: "I sleep in my bed.", d: "Furniture you sleep on." },
    { w: "box", s: "The toys are in the box.", d: "A container with sides and a lid." },
    { w: "fox", s: "The fox has a bushy tail.", d: "A wild animal that looks like a small dog." },
    { w: "pig", s: "The pig rolled in the mud.", d: "A farm animal that says oink." },
    { w: "fish", s: "The fish swims in water.", d: "An animal that lives in water and has fins." },
    { w: "ball", s: "Throw the ball to me.", d: "A round toy you can throw or bounce." },
    { w: "tree", s: "A bird sat in the tree.", d: "A tall plant with a trunk and leaves." },
    { w: "milk", s: "I drink milk every morning.", d: "A white drink that comes from cows." },
    { w: "frog", s: "The frog jumped into the pond.", d: "A green animal that hops and says ribbit." },
    { w: "star", s: "I see a star in the sky.", d: "A bright light far up in the night sky." },
    { w: "book", s: "I read a book before bed.", d: "Pages with words and pictures to read." },
    { w: "rain", s: "The rain made the ground wet.", d: "Water that falls from clouds." },
    { w: "cake", s: "We ate cake at the party.", d: "A sweet baked treat for birthdays." },
    { w: "duck", s: "The duck swam in the lake.", d: "A bird that says quack and likes water." },
    { w: "moon", s: "The moon glows at night.", d: "The round light we see in the night sky." },
    { w: "jump", s: "Can you jump over the rope?", d: "To push off the ground into the air." },
    { w: "hand", s: "Wave your hand hello.", d: "The part of your body at the end of your arm." },
    { w: "nest", s: "The bird built a nest.", d: "A home birds make for their eggs." },
    { w: "leaf", s: "A green leaf fell from the tree.", d: "The flat green part of a plant." },
    { w: "shoe", s: "Tie your shoe so you don't trip.", d: "What you wear on your foot." },
    { w: "bird", s: "The bird can fly high.", d: "An animal with feathers and wings." },
    { w: "rock", s: "I found a smooth rock.", d: "A hard piece of stone." }
  ],

  "Level 2 — Building Up": [
    { w: "apple", s: "An apple a day is healthy.", d: "A round fruit that is red or green." },
    { w: "happy", s: "I feel happy on my birthday.", d: "Feeling glad and full of joy." },
    { w: "water", s: "Plants need water to grow.", d: "The clear liquid we drink." },
    { w: "house", s: "We live in a big house.", d: "A building where people live." },
    { w: "table", s: "Put the plate on the table.", d: "Furniture with a flat top and legs." },
    { w: "chair", s: "Sit on the chair, please.", d: "A seat for one person." },
    { w: "green", s: "The grass is green.", d: "The color of leaves and grass." },
    { w: "smile", s: "Your smile is bright.", d: "To turn your mouth up when you are happy." },
    { w: "cloud", s: "A fluffy cloud floated by.", d: "White fluffy shapes in the sky." },
    { w: "grass", s: "We played on the green grass.", d: "Green plants that cover the ground." },
    { w: "sleep", s: "I sleep eight hours each night.", d: "To rest with your eyes closed." },
    { w: "mouse", s: "A tiny mouse ran by.", d: "A small animal with a long tail." },
    { w: "horse", s: "The horse ran in the field.", d: "A big animal people can ride." },
    { w: "candy", s: "I love sweet candy.", d: "A sweet treat made of sugar." },
    { w: "paper", s: "I drew on the paper.", d: "A thin flat sheet you write on." },
    { w: "pencil", s: "Write with your pencil.", d: "A tool you use to write or draw." },
    { w: "school", s: "I go to school to learn.", d: "A place where children go to learn." },
    { w: "friend", s: "My friend plays with me.", d: "Someone you like and spend time with." },
    { w: "family", s: "My family loves me.", d: "The people you are related to." },
    { w: "garden", s: "Flowers grow in the garden.", d: "A place where plants and flowers grow." },
    { w: "rabbit", s: "The rabbit hopped away.", d: "A furry animal with long ears." },
    { w: "monkey", s: "The monkey climbed the tree.", d: "An animal that swings and climbs." },
    { w: "yellow", s: "The banana is yellow.", d: "The color of the sun and bananas." },
    { w: "purple", s: "I painted the sky purple.", d: "A color made by mixing red and blue." },
    { w: "orange", s: "I ate a juicy orange.", d: "A round fruit, also a color." },
    { w: "winter", s: "It snows in winter.", d: "The cold season of the year." },
    { w: "summer", s: "We swim in summer.", d: "The warm, sunny season." },
    { w: "flower", s: "The flower smells sweet.", d: "The pretty, colorful part of a plant." },
    { w: "window", s: "Look out the window.", d: "An opening in a wall with glass." },
    { w: "pillow", s: "I rest my head on a soft pillow.", d: "A soft cushion for your head." },
    { w: "cookie", s: "I baked a chocolate cookie.", d: "A small, sweet, flat baked treat." },
    { w: "turtle", s: "The turtle moves slowly.", d: "An animal with a hard shell." },
    { w: "dragon", s: "The dragon breathed fire.", d: "A make-believe animal that flies and breathes fire." },
    { w: "pocket", s: "I keep a coin in my pocket.", d: "A small bag sewn into clothes." },
    { w: "basket", s: "Put the eggs in the basket.", d: "A container with a handle for carrying things." }
  ],

  "Level 3 — Bee Challenge": [
    { w: "animal", s: "A lion is a wild animal.", d: "A living creature that is not a plant." },
    { w: "because", s: "I smiled because I was happy.", d: "A word that tells the reason why." },
    { w: "weather", s: "The weather is sunny today.", d: "What it is like outside, like rain or sun." },
    { w: "favorite", s: "Blue is my favorite color.", d: "The one you like the most." },
    { w: "beautiful", s: "The sunset is beautiful.", d: "Very pretty and nice to look at." },
    { w: "elephant", s: "The elephant has a long trunk.", d: "A huge gray animal with big ears." },
    { w: "vacation", s: "We went to the beach on vacation.", d: "A trip you take for fun and rest." },
    { w: "remember", s: "Please remember to brush your teeth.", d: "To keep something in your mind." },
    { w: "tomorrow", s: "We will play tomorrow.", d: "The day after today." },
    { w: "together", s: "We worked together as a team.", d: "With each other, not alone." },
    { w: "neighbor", s: "My neighbor lives next door.", d: "A person who lives near you." },
    { w: "alphabet", s: "The alphabet has 26 letters.", d: "All the letters from A to Z." },
    { w: "dinosaur", s: "The dinosaur lived long ago.", d: "A giant animal from long, long ago." },
    { w: "umbrella", s: "I used an umbrella in the rain.", d: "A cover that keeps rain off you." },
    { w: "birthday", s: "Today is my birthday.", d: "The day you were born, celebrated each year." },
    { w: "chocolate", s: "I love warm chocolate milk.", d: "A sweet brown treat made from cocoa." },
    { w: "butterfly", s: "A butterfly landed on the flower.", d: "An insect with big, colorful wings." },
    { w: "adventure", s: "We went on a fun adventure.", d: "An exciting trip or experience." },
    { w: "important", s: "Sleep is important for your health.", d: "Something that matters a lot." },
    { w: "different", s: "Each snowflake is different.", d: "Not the same as another." },
    { w: "wonderful", s: "We had a wonderful day.", d: "Very good and full of joy." },
    { w: "celebrate", s: "We celebrate holidays with our family.", d: "To do something fun for a special day." },
    { w: "playground", s: "We ran at the playground.", d: "An outdoor place with swings and slides." },
    { w: "breakfast", s: "I eat breakfast in the morning.", d: "The first meal of the day." },
    { w: "kangaroo", s: "A kangaroo hops on its strong legs.", d: "An animal that hops and carries babies in a pouch." },
    { w: "library", s: "We borrow books at the library.", d: "A place full of books you can read or borrow." },
    { w: "calendar", s: "I marked my birthday on the calendar.", d: "A chart that shows the days and months." },
    { w: "sandwich", s: "I made a peanut butter sandwich.", d: "Food between two slices of bread." },
    { w: "question", s: "I raised my hand to ask a question.", d: "Something you ask to learn an answer." },
    { w: "surprise", s: "The gift was a big surprise.", d: "Something you did not expect." },
    { w: "treasure", s: "The pirates dug up the treasure.", d: "Something valuable, like gold or jewels." },
    { w: "exercise", s: "Exercise keeps your body strong.", d: "Moving your body to stay healthy." },
    { w: "mountain", s: "We climbed the tall mountain.", d: "A very tall, rocky hill." },
    { w: "hospital", s: "Doctors work at the hospital.", d: "A place where sick people get better." },
    { w: "telephone", s: "I called Grandma on the telephone.", d: "A device used to talk to people far away." }
  ],

  "Level 4 — Tricky Spellers": [
    { w: "knee", s: "I scraped my knee when I fell.", d: "The bendy middle part of your leg." },
    { w: "knife", s: "Be careful with the sharp knife.", d: "A tool with a blade used to cut." },
    { w: "write", s: "I write my name at the top.", d: "To make letters and words." },
    { w: "wrong", s: "That answer was wrong.", d: "Not correct." },
    { w: "listen", s: "Please listen to the teacher.", d: "To pay attention with your ears." },
    { w: "island", s: "The island is in the middle of the sea.", d: "Land with water all around it." },
    { w: "castle", s: "The king lives in a castle.", d: "A big stone home for a king or queen." },
    { w: "thumb", s: "I have a thumb on each hand.", d: "The short, thick finger on your hand." },
    { w: "comb", s: "Use a comb to fix your hair.", d: "A tool with teeth to neaten your hair." },
    { w: "ghost", s: "The ghost in the story was friendly.", d: "A make-believe spirit, like at Halloween." },
    { w: "build", s: "Let's build a tower with blocks.", d: "To make something by putting parts together." },
    { w: "guess", s: "Can you guess my favorite color?", d: "To give an answer without being sure." },
    { w: "honest", s: "An honest person tells the truth.", d: "Truthful and fair." },
    { w: "hour", s: "We waited for one hour.", d: "A length of time, 60 minutes." },
    { w: "scissors", s: "I cut the paper with scissors.", d: "A tool with two blades that cuts paper." },
    { w: "science", s: "We did a science experiment.", d: "Learning about how the world works." },
    { w: "favorite", s: "Pizza is my favorite food.", d: "The one you like best of all." },
    { w: "enough", s: "I have had enough food, thank you.", d: "As much as you need." },
    { w: "though", s: "It was cold, though I was warm inside.", d: "A word that means 'even so'." },
    { w: "through", s: "We walked through the tunnel.", d: "Going in one side and out the other." },
    { w: "beautiful", s: "What a beautiful rainbow!", d: "Very lovely to look at." },
    { w: "necessary", s: "Sleep is necessary to feel good.", d: "Needed; you must have it." },
    { w: "Wednesday", s: "We have art class on Wednesday.", d: "The day in the middle of the week." },
    { w: "February", s: "My birthday is in February.", d: "The second month of the year." },
    { w: "chocolate", s: "She baked a chocolate cake.", d: "A sweet brown food made from cocoa beans." },
    { w: "definitely", s: "I will definitely come to your party.", d: "For sure; without a doubt." },
    { w: "beautiful", s: "The garden looks beautiful in spring.", d: "Very pretty and pleasing." },
    { w: "restaurant", s: "We ate dinner at a restaurant.", d: "A place where you buy and eat meals." },
    { w: "muscle", s: "Lifting toys makes your muscle strong.", d: "The part of your body that helps you move." },
    { w: "rhythm", s: "Clap to the rhythm of the song.", d: "A pattern of beats in music." }
  ],

  "🐝 Scripps One Bee — Official List (125 words)": [
    { w: "punting", s: "The player practiced punting the football down the field.", d: "Kicking a football that you drop from your hands." },
    { w: "crowd", s: "A big crowd cheered at the game.", d: "A large group of people in one place." },
    { w: "secret", s: "I will keep your secret safe.", d: "Something you keep hidden and do not tell." },
    { w: "fumble", s: "Do not fumble the ball when you catch it.", d: "To drop or lose your grip on something." },
    { w: "pond", s: "Ducks swam across the pond.", d: "A small body of still water." },
    { w: "health", s: "Eating vegetables is good for your health.", d: "How well and strong your body is." },
    { w: "pardon", s: "Pardon me, may I get by?", d: "To forgive, or to say 'excuse me'." },
    { w: "shake", s: "Shake the bottle before you pour.", d: "To move quickly back and forth." },
    { w: "kiddo", s: "Great job, kiddo!", d: "A friendly name for a child." },
    { w: "proof", s: "The footprints were proof a dog walked by.", d: "Something that shows what is true." },
    { w: "gorp", s: "We packed gorp for our hike.", d: "A trail-mix snack of nuts and raisins." },
    { w: "town", s: "We drove into town to buy groceries.", d: "A place with homes, shops, and streets." },
    { w: "bingo", s: "She shouted 'bingo!' when she won.", d: "A game where you match numbers on a card." },
    { w: "clever", s: "The clever fox found a way out.", d: "Smart and quick at figuring things out." },
    { w: "inside", s: "Stay inside when it rains.", d: "On the inner part of something." },
    { w: "reply", s: "Please reply to my question.", d: "To answer." },
    { w: "frozen", s: "The frozen pond was covered in ice.", d: "Turned hard and icy from the cold." },
    { w: "special", s: "Today is a special day.", d: "Better or different from the usual." },
    { w: "film", s: "We watched a funny film.", d: "A movie." },
    { w: "results", s: "We waited for the game results.", d: "What happens at the end; the answers." },
    { w: "soda", s: "I had a cold soda with lunch.", d: "A sweet, fizzy drink." },
    { w: "seal", s: "The seal clapped its flippers.", d: "A sea animal with flippers; or to close something tight." },
    { w: "twirled", s: "She twirled in her new dress.", d: "Spun around quickly." },
    { w: "admit", s: "I admit I made a mistake.", d: "To say that something is true." },
    { w: "grown-ups", s: "The grown-ups talked while we played.", d: "Adults; people who are all grown." },
    { w: "pieces", s: "The puzzle has one hundred pieces.", d: "Parts of a whole." },
    { w: "brass", s: "The trumpet is made of brass.", d: "A shiny yellow metal." },
    { w: "onshore", s: "The little boat sailed onshore.", d: "On or toward the land by the sea." },
    { w: "stunts", s: "The biker did cool stunts.", d: "Daring tricks." },
    { w: "deny", s: "He will deny eating the cookies.", d: "To say something is not true." },
    { w: "jolly", s: "Santa is a jolly fellow.", d: "Happy and cheerful." },
    { w: "powder", s: "Snow fell like soft powder.", d: "Tiny dry bits, like dust." },
    { w: "walnut", s: "I cracked open a walnut.", d: "A wrinkly nut in a hard shell." },
    { w: "sawdust", s: "The workshop floor was covered in sawdust.", d: "Tiny bits of wood made by sawing." },
    { w: "flustered", s: "She got flustered when she lost her place.", d: "Upset and a little confused." },
    { w: "barber", s: "The barber gave me a haircut.", d: "A person who cuts hair." },
    { w: "chimes", s: "The wind chimes rang softly.", d: "Bells that make musical sounds." },
    { w: "cabin", s: "We stayed in a cabin in the woods.", d: "A small wooden house." },
    { w: "faint", s: "I heard a faint sound far away.", d: "Weak or hard to see or hear." },
    { w: "manger", s: "The cow ate hay from the manger.", d: "A box that holds food for farm animals." },
    { w: "peppermint", s: "I sucked on a peppermint candy.", d: "A cool, minty flavor." },
    { w: "broth", s: "Warm broth feels good when you are sick.", d: "A thin soup made by boiling food." },
    { w: "ash", s: "Gray ash floated up from the fire.", d: "The gray dust left after something burns." },
    { w: "flame", s: "The candle flame flickered.", d: "The bright, hot part of a fire." },
    { w: "grits", s: "We ate grits for breakfast.", d: "Ground corn cooked into a soft food." },
    { w: "cliff", s: "Do not stand too close to the cliff.", d: "A tall, steep rock wall." },
    { w: "hem", s: "Mom sewed the hem of my pants.", d: "The folded edge of cloth." },
    { w: "candles", s: "We lit the candles on the cake.", d: "Sticks of wax with a flame on top." },
    { w: "brim", s: "The cup was full to the brim.", d: "The top edge of a cup, or the edge of a hat." },
    { w: "plot", s: "The plot of the movie was exciting.", d: "The story of a book or movie; or a small piece of land." },
    { w: "desk", s: "My books are on my desk.", d: "A table for writing or working." },
    { w: "bobcat", s: "A bobcat lives in the forest.", d: "A wild cat with a short tail." },
    { w: "polo", s: "They played polo on horseback.", d: "A ball game played while riding horses." },
    { w: "roller", s: "I painted the wall with a roller.", d: "A round tube that rolls." },
    { w: "stark", s: "The empty room looked stark and bare.", d: "Plain and bare." },
    { w: "drum", s: "He banged the drum loudly.", d: "An instrument you hit to make a beat." },
    { w: "snarl", s: "The dog gave a low snarl.", d: "An angry growl; or a tangle." },
    { w: "argue", s: "Please do not argue over the toy.", d: "To disagree out loud." },
    { w: "loppers", s: "Dad trimmed the bush with loppers.", d: "Big garden scissors for cutting branches." },
    { w: "petal", s: "A pink petal fell from the rose.", d: "One soft part of a flower." },
    { w: "giant", s: "The giant was taller than the trees.", d: "Something very, very big." },
    { w: "sniffle", s: "I sniffle when I have a cold.", d: "To breathe in noisily through your nose." },
    { w: "mouth", s: "Cover your mouth when you cough.", d: "The part of your face you eat and talk with." },
    { w: "filters", s: "The fish tank has filters to clean the water.", d: "Things that clean what passes through them." },
    { w: "cone", s: "I ate ice cream from a cone.", d: "A shape that is round at the bottom and pointy on top." },
    { w: "never", s: "I will never give up.", d: "Not at any time." },
    { w: "silly", s: "We made silly faces.", d: "Funny and playful." },
    { w: "Monday", s: "We go back to school on Monday.", d: "The first day of the school week." },
    { w: "grub", s: "A fat grub wiggled in the dirt.", d: "A baby insect, like a larva." },
    { w: "hook", s: "Hang your coat on the hook.", d: "A bent piece used to catch or hang things." },
    { w: "number", s: "Seven is my favorite number.", d: "A word or sign that tells how many." },
    { w: "cooking", s: "Dad is cooking dinner.", d: "Making food with heat." },
    { w: "amazed", s: "I was amazed by the magic trick.", d: "Very surprised and impressed." },
    { w: "collect", s: "I collect shiny rocks.", d: "To gather things together." },
    { w: "local", s: "We shop at the local store.", d: "From the nearby area." },
    { w: "proper", s: "Use proper manners at the table.", d: "Correct and right." },
    { w: "basement", s: "Our toys are kept in the basement.", d: "A room below the ground floor." },
    { w: "ripple", s: "A ripple spread across the pond.", d: "A tiny wave." },
    { w: "feats", s: "The acrobat did daring feats.", d: "Brave or amazing actions." },
    { w: "plumbing", s: "The plumbing carries water to the sink.", d: "The pipes that carry water in a building." },
    { w: "stubborn", s: "The stubborn mule would not move.", d: "Not willing to change your mind." },
    { w: "adrift", s: "The empty boat was adrift on the sea.", d: "Floating along with no control." },
    { w: "sweeten", s: "Add honey to sweeten your tea.", d: "To make something taste sweeter." },
    { w: "neon", s: "The sign glowed in bright neon colors.", d: "A bright, glowing color or light." },
    { w: "beeswax", s: "The candle is made of beeswax.", d: "The wax bees make for their honeycomb." },
    { w: "social", s: "Dogs are friendly, social animals.", d: "Liking to be around other people or animals." },
    { w: "behold", s: "Behold the beautiful rainbow!", d: "To look at something amazing." },
    { w: "mix", s: "Mix the flour and the sugar.", d: "To stir things together." },
    { w: "drool", s: "The hungry dog began to drool.", d: "Spit that drips from your mouth." },
    { w: "understand", s: "I understand the lesson now.", d: "To know what something means." },
    { w: "sound", s: "I heard the sound of birds.", d: "Something you hear." },
    { w: "benches", s: "We sat on the park benches.", d: "Long seats for more than one person." },
    { w: "shrugged", s: "She shrugged when I asked why.", d: "Lifted your shoulders to say 'I do not know'." },
    { w: "still", s: "Sit still while I take your picture.", d: "Not moving." },
    { w: "pranks", s: "We played funny pranks on April Fools' Day.", d: "Silly tricks played on someone." },
    { w: "smiled", s: "He smiled when he opened the gift.", d: "Made a happy face." },
    { w: "peach", s: "I bit into a juicy peach.", d: "A soft, fuzzy, sweet fruit." },
    { w: "pie", s: "We ate apple pie for dessert.", d: "A baked dish with a crust and a filling." },
    { w: "size", s: "What size shoe do you wear?", d: "How big or small something is." },
    { w: "hall", s: "Walk quietly in the hall.", d: "A long passage in a building." },
    { w: "jangled", s: "The keys jangled in his pocket.", d: "Made a noisy ringing sound." },
    { w: "chain", s: "The swing hung from a long chain.", d: "A row of metal links joined together." },
    { w: "workhorse", s: "The old truck is a real workhorse.", d: "Someone or something that works very hard." },
    { w: "antennas", s: "The ant's antennas wiggled.", d: "Feelers on a bug's head; or rods that catch signals." },
    { w: "honest", s: "An honest person tells the truth.", d: "Truthful and fair." },
    { w: "holler", s: "Holler if you need help.", d: "To shout loudly." },
    { w: "billboard", s: "The billboard showed a giant burger.", d: "A huge sign by the road." },
    { w: "chicken", s: "The chicken pecked at the seeds.", d: "A farm bird that lays eggs." },
    { w: "puppets", s: "We put on a show with puppets.", d: "Dolls you move with your hands or strings." },
    { w: "waited", s: "We waited for the bus.", d: "Stayed until something happened." },
    { w: "finish", s: "Finish your homework first.", d: "To complete something; the end." },
    { w: "cheer", s: "We cheer for our team.", d: "To shout happily to support someone." },
    { w: "twisty", s: "We drove up the twisty mountain road.", d: "Full of turns and bends." },
    { w: "chips", s: "I love crunchy potato chips.", d: "Thin, crispy snack slices." },
    { w: "scoop", s: "Scoop the ice cream into a bowl.", d: "To lift something up with a spoon or your hands." },
    { w: "rover", s: "The rover explored the rocky ground.", d: "One who wanders; or a robot vehicle." },
    { w: "forgive", s: "I forgive you for the mistake.", d: "To stop being angry at someone." },
    { w: "ribbon", s: "She tied a ribbon in her hair.", d: "A thin strip of cloth for tying or decorating." },
    { w: "shoo", s: "Shoo the fly off the food.", d: "To wave something away." },
    { w: "greedy", s: "The greedy goblin grabbed all the gold.", d: "Wanting much more than you need." },
    { w: "beam", s: "A beam of sunlight came through the window.", d: "A ray of light; or a long support." },
    { w: "crew", s: "The boat's crew rowed hard.", d: "A team that works together." },
    { w: "crate", s: "The apples came in a wooden crate.", d: "A large wooden box." },
    { w: "hotel", s: "We stayed in a hotel on our trip.", d: "A place where travelers pay to sleep." },
    { w: "stray", s: "A stray cat showed up at our door.", d: "A lost pet; or to wander off." }
  ]
};
