// Spelling Bee word bank.
// Each word: w = word, s = example sentence, d = simple kid-friendly definition.
// Levels grow harder. Great for ages 6-8 (Scripps-style early grade bee).

const WORD_LEVELS = {
  "Level 1 — Starter (3-4 letters)": [
    { w: "cat", s: "The cat sat on the mat.", d: "A small furry pet that says meow." },
    { w: "dog", s: "My dog likes to run.", d: "A friendly pet that barks." },
    { w: "sun", s: "The sun is bright today.", d: "The big star that gives us light and warmth." },
    { w: "hat", s: "Put on your hat before you go out.", d: "Something you wear on your head." },
    { w: "red", s: "The apple is red.", d: "The color of a strawberry or fire truck." },
    { w: "run", s: "I can run very fast.", d: "To move quickly on your feet." },
    { w: "big", s: "The elephant is big.", d: "Large in size." },
    { w: "cup", s: "She drank milk from the cup.", d: "A small container you drink from." },
    { w: "bed", s: "I sleep in my bed.", d: "Furniture you sleep on." },
    { w: "box", s: "The toys are in the box.", d: "A container with sides and a lid." },
    { w: "fox", s: "The fox has a bushy tail.", d: "A wild animal that looks like a small dog." },
    { w: "pig", s: "The pig rolled in the mud.", d: "A farm animal that says oink." },
    { w: "fish", s: "The fish swims in water.", d: "An animal that lives in water and has fins." },
    { w: "ball", s: "Throw the ball to me.", d: "A round toy you can throw or bounce." },
    { w: "tree", s: "A bird sat in the tree.", d: "A tall plant with a trunk and leaves." },
    { w: "milk", s: "I drink milk every morning.", d: "A white drink that comes from cows." },
    { w: "frog", s: "The frog jumped into the pond.", d: "A green animal that hops and says ribbit." },
    { w: "star", s: "I see a star in the sky.", d: "A bright light far up in the night sky." },
    { w: "book", s: "I read a book before bed.", d: "Pages with words and pictures to read." },
    { w: "rain", s: "The rain made the ground wet.", d: "Water that falls from clouds." },
    { w: "cake", s: "We ate cake at the party.", d: "A sweet baked treat for birthdays." },
    { w: "duck", s: "The duck swam in the lake.", d: "A bird that says quack and likes water." },
    { w: "moon", s: "The moon glows at night.", d: "The round light we see in the night sky." },
    { w: "jump", s: "Can you jump over the rope?", d: "To push off the ground into the air." },
    { w: "hand", s: "Wave your hand hello.", d: "The part of your body at the end of your arm." },
    { w: "nest", s: "The bird built a nest.", d: "A home birds make for their eggs." },
    { w: "leaf", s: "A green leaf fell from the tree.", d: "The flat green part of a plant." },
    { w: "shoe", s: "Tie your shoe so you don't trip.", d: "What you wear on your foot." },
    { w: "bird", s: "The bird can fly high.", d: "An animal with feathers and wings." },
    { w: "rock", s: "I found a smooth rock.", d: "A hard piece of stone." }
  ],

  "Level 2 — Building Up": [
    { w: "apple", s: "An apple a day is healthy.", d: "A round fruit that is red or green." },
    { w: "happy", s: "I feel happy on my birthday.", d: "Feeling glad and full of joy." },
    { w: "water", s: "Plants need water to grow.", d: "The clear liquid we drink." },
    { w: "house", s: "We live in a big house.", d: "A building where people live." },
    { w: "table", s: "Put the plate on the table.", d: "Furniture with a flat top and legs." },
    { w: "chair", s: "Sit on the chair, please.", d: "A seat for one person." },
    { w: "green", s: "The grass is green.", d: "The color of leaves and grass." },
    { w: "smile", s: "Your smile is bright.", d: "To turn your mouth up when you are happy." },
    { w: "cloud", s: "A fluffy cloud floated by.", d: "White fluffy shapes in the sky." },
    { w: "grass", s: "We played on the green grass.", d: "Green plants that cover the ground." },
    { w: "sleep", s: "I sleep eight hours each night.", d: "To rest with your eyes closed." },
    { w: "mouse", s: "A tiny mouse ran by.", d: "A small animal with a long tail." },
    { w: "horse", s: "The horse ran in the field.", d: "A big animal people can ride." },
    { w: "candy", s: "I love sweet candy.", d: "A sweet treat made of sugar." },
    { w: "paper", s: "I drew on the paper.", d: "A thin flat sheet you write on." },
    { w: "pencil", s: "Write with your pencil.", d: "A tool you use to write or draw." },
    { w: "school", s: "I go to school to learn.", d: "A place where children go to learn." },
    { w: "friend", s: "My friend plays with me.", d: "Someone you like and spend time with." },
    { w: "family", s: "My family loves me.", d: "The people you are related to." },
    { w: "garden", s: "Flowers grow in the garden.", d: "A place where plants and flowers grow." },
    { w: "rabbit", s: "The rabbit hopped away.", d: "A furry animal with long ears." },
    { w: "monkey", s: "The monkey climbed the tree.", d: "An animal that swings and climbs." },
    { w: "yellow", s: "The banana is yellow.", d: "The color of the sun and bananas." },
    { w: "purple", s: "I painted the sky purple.", d: "A color made by mixing red and blue." },
    { w: "orange", s: "I ate a juicy orange.", d: "A round fruit, also a color." },
    { w: "winter", s: "It snows in winter.", d: "The cold season of the year." },
    { w: "summer", s: "We swim in summer.", d: "The warm, sunny season." },
    { w: "flower", s: "The flower smells sweet.", d: "The pretty, colorful part of a plant." },
    { w: "window", s: "Look out the window.", d: "An opening in a wall with glass." },
    { w: "pillow", s: "I rest my head on a soft pillow.", d: "A soft cushion for your head." },
    { w: "cookie", s: "I baked a chocolate cookie.", d: "A small, sweet, flat baked treat." },
    { w: "turtle", s: "The turtle moves slowly.", d: "An animal with a hard shell." },
    { w: "dragon", s: "The dragon breathed fire.", d: "A make-believe animal that flies and breathes fire." },
    { w: "pocket", s: "I keep a coin in my pocket.", d: "A small bag sewn into clothes." },
    { w: "basket", s: "Put the eggs in the basket.", d: "A container with a handle for carrying things." }
  ],

  "Level 3 — Bee Challenge": [
    { w: "animal", s: "A lion is a wild animal.", d: "A living creature that is not a plant." },
    { w: "because", s: "I smiled because I was happy.", d: "A word that tells the reason why." },
    { w: "weather", s: "The weather is sunny today.", d: "What it is like outside, like rain or sun." },
    { w: "favorite", s: "Blue is my favorite color.", d: "The one you like the most." },
    { w: "beautiful", s: "The sunset is beautiful.", d: "Very pretty and nice to look at." },
    { w: "elephant", s: "The elephant has a long trunk.", d: "A huge gray animal with big ears." },
    { w: "vacation", s: "We went to the beach on vacation.", d: "A trip you take for fun and rest." },
    { w: "remember", s: "Please remember to brush your teeth.", d: "To keep something in your mind." },
    { w: "tomorrow", s: "We will play tomorrow.", d: "The day after today." },
    { w: "together", s: "We worked together as a team.", d: "With each other, not alone." },
    { w: "neighbor", s: "My neighbor lives next door.", d: "A person who lives near you." },
    { w: "alphabet", s: "The alphabet has 26 letters.", d: "All the letters from A to Z." },
    { w: "dinosaur", s: "The dinosaur lived long ago.", d: "A giant animal from long, long ago." },
    { w: "umbrella", s: "I used an umbrella in the rain.", d: "A cover that keeps rain off you." },
    { w: "birthday", s: "Today is my birthday.", d: "The day you were born, celebrated each year." },
    { w: "chocolate", s: "I love warm chocolate milk.", d: "A sweet brown treat made from cocoa." },
    { w: "butterfly", s: "A butterfly landed on the flower.", d: "An insect with big, colorful wings." },
    { w: "adventure", s: "We went on a fun adventure.", d: "An exciting trip or experience." },
    { w: "important", s: "Sleep is important for your health.", d: "Something that matters a lot." },
    { w: "different", s: "Each snowflake is different.", d: "Not the same as another." },
    { w: "wonderful", s: "We had a wonderful day.", d: "Very good and full of joy." },
    { w: "celebrate", s: "We celebrate holidays with our family.", d: "To do something fun for a special day." },
    { w: "playground", s: "We ran at the playground.", d: "An outdoor place with swings and slides." },
    { w: "breakfast", s: "I eat breakfast in the morning.", d: "The first meal of the day." },
    { w: "kangaroo", s: "A kangaroo hops on its strong legs.", d: "An animal that hops and carries babies in a pouch." },
    { w: "library", s: "We borrow books at the library.", d: "A place full of books you can read or borrow." },
    { w: "calendar", s: "I marked my birthday on the calendar.", d: "A chart that shows the days and months." },
    { w: "sandwich", s: "I made a peanut butter sandwich.", d: "Food between two slices of bread." },
    { w: "question", s: "I raised my hand to ask a question.", d: "Something you ask to learn an answer." },
    { w: "surprise", s: "The gift was a big surprise.", d: "Something you did not expect." },
    { w: "treasure", s: "The pirates dug up the treasure.", d: "Something valuable, like gold or jewels." },
    { w: "exercise", s: "Exercise keeps your body strong.", d: "Moving your body to stay healthy." },
    { w: "mountain", s: "We climbed the tall mountain.", d: "A very tall, rocky hill." },
    { w: "hospital", s: "Doctors work at the hospital.", d: "A place where sick people get better." },
    { w: "telephone", s: "I called Grandma on the telephone.", d: "A device used to talk to people far away." }
  ],

  "Level 4 — Tricky Spellers": [
    { w: "knee", s: "I scraped my knee when I fell.", d: "The bendy middle part of your leg." },
    { w: "knife", s: "Be careful with the sharp knife.", d: "A tool with a blade used to cut." },
    { w: "write", s: "I write my name at the top.", d: "To make letters and words." },
    { w: "wrong", s: "That answer was wrong.", d: "Not correct." },
    { w: "listen", s: "Please listen to the teacher.", d: "To pay attention with your ears." },
    { w: "island", s: "The island is in the middle of the sea.", d: "Land with water all around it." },
    { w: "castle", s: "The king lives in a castle.", d: "A big stone home for a king or queen." },
    { w: "thumb", s: "I have a thumb on each hand.", d: "The short, thick finger on your hand." },
    { w: "comb", s: "Use a comb to fix your hair.", d: "A tool with teeth to neaten your hair." },
    { w: "ghost", s: "The ghost in the story was friendly.", d: "A make-believe spirit, like at Halloween." },
    { w: "build", s: "Let's build a tower with blocks.", d: "To make something by putting parts together." },
    { w: "guess", s: "Can you guess my favorite color?", d: "To give an answer without being sure." },
    { w: "honest", s: "An honest person tells the truth.", d: "Truthful and fair." },
    { w: "hour", s: "We waited for one hour.", d: "A length of time, 60 minutes." },
    { w: "scissors", s: "I cut the paper with scissors.", d: "A tool with two blades that cuts paper." },
    { w: "science", s: "We did a science experiment.", d: "Learning about how the world works." },
    { w: "favorite", s: "Pizza is my favorite food.", d: "The one you like best of all." },
    { w: "enough", s: "I have had enough food, thank you.", d: "As much as you need." },
    { w: "though", s: "It was cold, though I was warm inside.", d: "A word that means 'even so'." },
    { w: "through", s: "We walked through the tunnel.", d: "Going in one side and out the other." },
    { w: "beautiful", s: "What a beautiful rainbow!", d: "Very lovely to look at." },
    { w: "necessary", s: "Sleep is necessary to feel good.", d: "Needed; you must have it." },
    { w: "Wednesday", s: "We have art class on Wednesday.", d: "The day in the middle of the week." },
    { w: "February", s: "My birthday is in February.", d: "The second month of the year." },
    { w: "chocolate", s: "She baked a chocolate cake.", d: "A sweet brown food made from cocoa beans." },
    { w: "definitely", s: "I will definitely come to your party.", d: "For sure; without a doubt." },
    { w: "beautiful", s: "The garden looks beautiful in spring.", d: "Very pretty and pleasing." },
    { w: "restaurant", s: "We ate dinner at a restaurant.", d: "A place where you buy and eat meals." },
    { w: "muscle", s: "Lifting toys makes your muscle strong.", d: "The part of your body that helps you move." },
    { w: "rhythm", s: "Clap to the rhythm of the song.", d: "A pattern of beats in music." }
  ]
};
